-- Recepção de eventos Strava em tempo real.
-- Não altera atletas, tokens ou atividades existentes.

create table if not exists public.strava_webhook_config (
  id smallint primary key default 1 check (id = 1),
  verify_token text not null,
  apps_script_secret text not null,
  apps_script_url text not null,
  callback_url text not null,
  subscription_id bigint,
  modo text not null default 'shadow' check (modo in ('shadow', 'ativo', 'pausado')),
  criado_at timestamptz not null default now(),
  atualizado_at timestamptz not null default now()
);

create table if not exists public.strava_eventos_webhook (
  id bigint generated by default as identity primary key,
  subscription_id bigint not null,
  object_type text not null check (object_type in ('activity', 'athlete')),
  object_id bigint not null,
  aspect_type text not null check (aspect_type in ('create', 'update', 'delete')),
  owner_id bigint not null,
  updates jsonb not null default '{}'::jsonb,
  event_time bigint not null,
  payload jsonb not null,
  status text not null default 'recebido'
    check (status in ('recebido', 'espelho', 'processando', 'processado', 'falha', 'ignorado')),
  tentativas integer not null default 0 check (tentativas >= 0),
  ultimo_erro text,
  recebido_at timestamptz not null default now(),
  processado_at timestamptz,
  proxima_tentativa timestamptz,
  unique (subscription_id, object_type, object_id, aspect_type, event_time)
);

create index if not exists idx_strava_eventos_webhook_pendentes
  on public.strava_eventos_webhook (status, proxima_tentativa, recebido_at)
  where status in ('recebido', 'falha');

create index if not exists idx_strava_eventos_webhook_owner
  on public.strava_eventos_webhook (owner_id, recebido_at desc);

alter table public.strava_webhook_config enable row level security;
alter table public.strava_eventos_webhook enable row level security;

revoke all on table public.strava_webhook_config from public, anon, authenticated;
revoke all on table public.strava_eventos_webhook from public, anon, authenticated;
revoke all on sequence public.strava_eventos_webhook_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.strava_webhook_config to service_role;
grant select, insert, update, delete on table public.strava_eventos_webhook to service_role;
grant usage, select on sequence public.strava_eventos_webhook_id_seq to service_role;

comment on table public.strava_webhook_config is
  'Configuração privada do webhook Strava. Acesso exclusivo do service_role.';
comment on table public.strava_eventos_webhook is
  'Fila idempotente de eventos Strava; não armazena access_token nem refresh_token.';
